package defpackage;

import vigqyno.C0201;

/* renamed from: tv1  reason: default package */
public final class tv1 {
    public static final int abc_action_bar_title_item = 0;
    public static final int abc_action_bar_up_container = 0;
    public static final int abc_action_menu_item_layout = 0;
    public static final int abc_action_menu_layout = 0;
    public static final int abc_action_mode_bar = 0;
    public static final int abc_action_mode_close_item_material = 0;
    public static final int abc_activity_chooser_view = 0;
    public static final int abc_activity_chooser_view_list_item = 0;
    public static final int abc_alert_dialog_button_bar_material = 0;
    public static final int abc_alert_dialog_material = 0;
    public static final int abc_alert_dialog_title_material = 0;
    public static final int abc_cascading_menu_item_layout = 0;
    public static final int abc_dialog_title_material = 0;
    public static final int abc_expanded_menu_layout = 0;
    public static final int abc_list_menu_item_checkbox = 0;
    public static final int abc_list_menu_item_icon = 0;
    public static final int abc_list_menu_item_layout = 0;
    public static final int abc_list_menu_item_radio = 0;
    public static final int abc_popup_menu_header_item_layout = 0;
    public static final int abc_popup_menu_item_layout = 0;
    public static final int abc_screen_content_include = 0;
    public static final int abc_screen_simple = 0;
    public static final int abc_screen_simple_overlay_action_mode = 0;
    public static final int abc_screen_toolbar = 0;
    public static final int abc_search_dropdown_item_icons_2line = 0;
    public static final int abc_search_view = 0;
    public static final int abc_select_dialog_material = 0;
    public static final int abc_tooltip = 0;
    public static final int custom_dialog = 0;
    public static final int design_bottom_navigation_item = 0;
    public static final int design_bottom_sheet_dialog = 0;
    public static final int design_layout_snackbar = 0;
    public static final int design_layout_snackbar_include = 0;
    public static final int design_layout_tab_icon = 0;
    public static final int design_layout_tab_text = 0;
    public static final int design_menu_item_action_area = 0;
    public static final int design_navigation_item = 0;
    public static final int design_navigation_item_header = 0;
    public static final int design_navigation_item_separator = 0;
    public static final int design_navigation_item_subheader = 0;
    public static final int design_navigation_menu = 0;
    public static final int design_navigation_menu_item = 0;
    public static final int design_text_input_end_icon = 0;
    public static final int design_text_input_start_icon = 0;
    public static final int mtrl_alert_dialog = 0;
    public static final int mtrl_alert_dialog_actions = 0;
    public static final int mtrl_alert_dialog_title = 0;
    public static final int mtrl_alert_select_dialog_item = 0;
    public static final int mtrl_alert_select_dialog_multichoice = 0;
    public static final int mtrl_alert_select_dialog_singlechoice = 0;
    public static final int mtrl_calendar_day = 0;
    public static final int mtrl_calendar_day_of_week = 0;
    public static final int mtrl_calendar_days_of_week = 0;
    public static final int mtrl_calendar_horizontal = 0;
    public static final int mtrl_calendar_month = 0;
    public static final int mtrl_calendar_month_labeled = 0;
    public static final int mtrl_calendar_month_navigation = 0;
    public static final int mtrl_calendar_months = 0;
    public static final int mtrl_calendar_vertical = 0;
    public static final int mtrl_calendar_year = 0;
    public static final int mtrl_layout_snackbar = 0;
    public static final int mtrl_layout_snackbar_include = 0;
    public static final int mtrl_picker_actions = 0;
    public static final int mtrl_picker_dialog = 0;
    public static final int mtrl_picker_fullscreen = 0;
    public static final int mtrl_picker_header_dialog = 0;
    public static final int mtrl_picker_header_fullscreen = 0;
    public static final int mtrl_picker_header_selection_text = 0;
    public static final int mtrl_picker_header_title_text = 0;
    public static final int mtrl_picker_header_toggle = 0;
    public static final int mtrl_picker_text_input_date = 0;
    public static final int mtrl_picker_text_input_date_range = 0;
    public static final int notification_action = 0;
    public static final int notification_action_tombstone = 0;
    public static final int notification_template_custom_big = 0;
    public static final int notification_template_icon_group = 0;
    public static final int notification_template_part_chronometer = 0;
    public static final int notification_template_part_time = 0;
    public static final int select_dialog_item_material = 0;
    public static final int select_dialog_multichoice_material = 0;
    public static final int select_dialog_singlechoice_material = 0;
    public static final int support_simple_spinner_dropdown_item = 0;
    public static final int test_action_chip = 0;
    public static final int test_design_checkbox = 0;
    public static final int test_reflow_chipgroup = 0;
    public static final int test_toolbar = 0;
    public static final int test_toolbar_custom_background = 0;
    public static final int test_toolbar_elevation = 0;
    public static final int test_toolbar_surface = 0;
    public static final int text_view_with_line_height_from_appearance = 0;
    public static final int text_view_with_line_height_from_layout = 0;
    public static final int text_view_with_line_height_from_style = 0;
    public static final int text_view_with_theme_line_height = 0;
    public static final int text_view_without_line_height = 0;

    static {
        C0201.m83(tv1.class, 162);
    }
}
