package defpackage;

import vigqyno.C0201;

/* renamed from: vv1  reason: default package */
public final class vv1 {
    public static final int abc_action_bar_home_description = 0;
    public static final int abc_action_bar_up_description = 0;
    public static final int abc_action_menu_overflow_description = 0;
    public static final int abc_action_mode_done = 0;
    public static final int abc_activity_chooser_view_see_all = 0;
    public static final int abc_activitychooserview_choose_application = 0;
    public static final int abc_capital_off = 0;
    public static final int abc_capital_on = 0;
    public static final int abc_menu_alt_shortcut_label = 0;
    public static final int abc_menu_ctrl_shortcut_label = 0;
    public static final int abc_menu_delete_shortcut_label = 0;
    public static final int abc_menu_enter_shortcut_label = 0;
    public static final int abc_menu_function_shortcut_label = 0;
    public static final int abc_menu_meta_shortcut_label = 0;
    public static final int abc_menu_shift_shortcut_label = 0;
    public static final int abc_menu_space_shortcut_label = 0;
    public static final int abc_menu_sym_shortcut_label = 0;
    public static final int abc_prepend_shortcut_label = 0;
    public static final int abc_search_hint = 0;
    public static final int abc_searchview_description_clear = 0;
    public static final int abc_searchview_description_query = 0;
    public static final int abc_searchview_description_search = 0;
    public static final int abc_searchview_description_submit = 0;
    public static final int abc_searchview_description_voice = 0;
    public static final int abc_shareactionprovider_share_with = 0;
    public static final int abc_shareactionprovider_share_with_application = 0;
    public static final int abc_toolbar_collapse_description = 0;
    public static final int appbar_scrolling_view_behavior = 0;
    public static final int bottom_sheet_behavior = 0;
    public static final int character_counter_content_description = 0;
    public static final int character_counter_overflowed_content_description = 0;
    public static final int character_counter_pattern = 0;
    public static final int chip_text = 0;
    public static final int clear_text_end_icon_content_description = 0;
    public static final int error_icon_content_description = 0;
    public static final int exposed_dropdown_menu_content_description = 0;
    public static final int fab_transformation_scrim_behavior = 0;
    public static final int fab_transformation_sheet_behavior = 0;
    public static final int hide_bottom_view_on_scroll_behavior = 0;
    public static final int icon_content_description = 0;
    public static final int mtrl_badge_numberless_content_description = 0;
    public static final int mtrl_chip_close_icon_content_description = 0;
    public static final int mtrl_exceed_max_badge_number_suffix = 0;
    public static final int mtrl_picker_a11y_next_month = 0;
    public static final int mtrl_picker_a11y_prev_month = 0;
    public static final int mtrl_picker_announce_current_selection = 0;
    public static final int mtrl_picker_cancel = 0;
    public static final int mtrl_picker_confirm = 0;
    public static final int mtrl_picker_date_header_selected = 0;
    public static final int mtrl_picker_date_header_title = 0;
    public static final int mtrl_picker_date_header_unselected = 0;
    public static final int mtrl_picker_day_of_week_column_header = 0;
    public static final int mtrl_picker_invalid_format = 0;
    public static final int mtrl_picker_invalid_format_example = 0;
    public static final int mtrl_picker_invalid_format_use = 0;
    public static final int mtrl_picker_invalid_range = 0;
    public static final int mtrl_picker_navigate_to_year_description = 0;
    public static final int mtrl_picker_out_of_range = 0;
    public static final int mtrl_picker_range_header_only_end_selected = 0;
    public static final int mtrl_picker_range_header_only_start_selected = 0;
    public static final int mtrl_picker_range_header_selected = 0;
    public static final int mtrl_picker_range_header_title = 0;
    public static final int mtrl_picker_range_header_unselected = 0;
    public static final int mtrl_picker_save = 0;
    public static final int mtrl_picker_text_input_date_hint = 0;
    public static final int mtrl_picker_text_input_date_range_end_hint = 0;
    public static final int mtrl_picker_text_input_date_range_start_hint = 0;
    public static final int mtrl_picker_text_input_day_abbr = 0;
    public static final int mtrl_picker_text_input_month_abbr = 0;
    public static final int mtrl_picker_text_input_year_abbr = 0;
    public static final int mtrl_picker_toggle_to_calendar_input_mode = 0;
    public static final int mtrl_picker_toggle_to_day_selection = 0;
    public static final int mtrl_picker_toggle_to_text_input_mode = 0;
    public static final int mtrl_picker_toggle_to_year_selection = 0;
    public static final int password_toggle_content_description = 0;
    public static final int path_password_eye = 0;
    public static final int path_password_eye_mask_strike_through = 0;
    public static final int path_password_eye_mask_visible = 0;
    public static final int path_password_strike_through = 0;
    public static final int search_menu_title = 0;
    public static final int status_bar_notification_info_overflow = 0;

    static {
        C0201.m83(vv1.class, 128);
    }
}
