package net.alhazmy13.hijridatepicker;

import vigqyno.C0201;

public final class f {
    public static final int abc_action_bar_title_item = 0;
    public static final int abc_action_bar_up_container = 0;
    public static final int abc_action_menu_item_layout = 0;
    public static final int abc_action_menu_layout = 0;
    public static final int abc_action_mode_bar = 0;
    public static final int abc_action_mode_close_item_material = 0;
    public static final int abc_activity_chooser_view = 0;
    public static final int abc_activity_chooser_view_list_item = 0;
    public static final int abc_alert_dialog_button_bar_material = 0;
    public static final int abc_alert_dialog_material = 0;
    public static final int abc_alert_dialog_title_material = 0;
    public static final int abc_cascading_menu_item_layout = 0;
    public static final int abc_dialog_title_material = 0;
    public static final int abc_expanded_menu_layout = 0;
    public static final int abc_list_menu_item_checkbox = 0;
    public static final int abc_list_menu_item_icon = 0;
    public static final int abc_list_menu_item_layout = 0;
    public static final int abc_list_menu_item_radio = 0;
    public static final int abc_popup_menu_header_item_layout = 0;
    public static final int abc_popup_menu_item_layout = 0;
    public static final int abc_screen_content_include = 0;
    public static final int abc_screen_simple = 0;
    public static final int abc_screen_simple_overlay_action_mode = 0;
    public static final int abc_screen_toolbar = 0;
    public static final int abc_search_dropdown_item_icons_2line = 0;
    public static final int abc_search_view = 0;
    public static final int abc_select_dialog_material = 0;
    public static final int abc_tooltip = 0;
    public static final int design_bottom_navigation_item = 0;
    public static final int design_bottom_sheet_dialog = 0;
    public static final int design_layout_snackbar = 0;
    public static final int design_layout_snackbar_include = 0;
    public static final int design_layout_tab_icon = 0;
    public static final int design_layout_tab_text = 0;
    public static final int design_menu_item_action_area = 0;
    public static final int design_navigation_item = 0;
    public static final int design_navigation_item_header = 0;
    public static final int design_navigation_item_separator = 0;
    public static final int design_navigation_item_subheader = 0;
    public static final int design_navigation_menu = 0;
    public static final int design_navigation_menu_item = 0;
    public static final int hdp_mdtp_date_picker_dialog = 0;
    public static final int hdp_mdtp_date_picker_dialog_v2 = 0;
    public static final int hdp_mdtp_date_picker_header_view = 0;
    public static final int hdp_mdtp_date_picker_header_view_v2 = 0;
    public static final int hdp_mdtp_date_picker_selected_date = 0;
    public static final int hdp_mdtp_date_picker_selected_date_v2 = 0;
    public static final int hdp_mdtp_date_picker_view_animator = 0;
    public static final int hdp_mdtp_date_time_picker_dialog = 0;
    public static final int hdp_mdtp_done_button = 0;
    public static final int hdp_mdtp_hijri_date_picker_dialog = 0;
    public static final int hdp_mdtp_hijri_date_picker_dialog_v2 = 0;
    public static final int hdp_mdtp_hijri_date_picker_header_view = 0;
    public static final int hdp_mdtp_hijri_date_picker_header_view_v2 = 0;
    public static final int hdp_mdtp_hijri_date_picker_selected_date = 0;
    public static final int hdp_mdtp_hijri_date_picker_selected_date_v2 = 0;
    public static final int hdp_mdtp_hijri_date_picker_view_animator = 0;
    public static final int hdp_mdtp_hijri_year_label_text_view = 0;
    public static final int hdp_mdtp_time_header_label = 0;
    public static final int hdp_mdtp_time_picker_dialog = 0;
    public static final int hdp_mdtp_time_picker_dialog_v2 = 0;
    public static final int hdp_mdtp_time_title_view = 0;
    public static final int hdp_mdtp_time_title_view_v2 = 0;
    public static final int hdp_mdtp_year_label_text_view = 0;
    public static final int mtrl_layout_snackbar = 0;
    public static final int mtrl_layout_snackbar_include = 0;
    public static final int notification_action = 0;
    public static final int notification_action_tombstone = 0;
    public static final int notification_media_action = 0;
    public static final int notification_media_cancel_action = 0;
    public static final int notification_template_big_media = 0;
    public static final int notification_template_big_media_custom = 0;
    public static final int notification_template_big_media_narrow = 0;
    public static final int notification_template_big_media_narrow_custom = 0;
    public static final int notification_template_custom_big = 0;
    public static final int notification_template_icon_group = 0;
    public static final int notification_template_lines_media = 0;
    public static final int notification_template_media = 0;
    public static final int notification_template_media_custom = 0;
    public static final int notification_template_part_chronometer = 0;
    public static final int notification_template_part_time = 0;
    public static final int select_dialog_item_material = 0;
    public static final int select_dialog_multichoice_material = 0;
    public static final int select_dialog_singlechoice_material = 0;
    public static final int support_simple_spinner_dropdown_item = 0;

    static {
        C0201.m83(f.class, 187);
    }
}
