package com.eddieowens;

import vigqyno.C0201;

public final class a {
    public static final int abc_background_cache_hint_selector_material_dark = 0;
    public static final int abc_background_cache_hint_selector_material_light = 0;
    public static final int abc_btn_colored_borderless_text_material = 0;
    public static final int abc_btn_colored_text_material = 0;
    public static final int abc_color_highlight_material = 0;
    public static final int abc_hint_foreground_material_dark = 0;
    public static final int abc_hint_foreground_material_light = 0;
    public static final int abc_input_method_navigation_guard = 0;
    public static final int abc_primary_text_disable_only_material_dark = 0;
    public static final int abc_primary_text_disable_only_material_light = 0;
    public static final int abc_primary_text_material_dark = 0;
    public static final int abc_primary_text_material_light = 0;
    public static final int abc_search_url_text = 0;
    public static final int abc_search_url_text_normal = 0;
    public static final int abc_search_url_text_pressed = 0;
    public static final int abc_search_url_text_selected = 0;
    public static final int abc_secondary_text_material_dark = 0;
    public static final int abc_secondary_text_material_light = 0;
    public static final int abc_tint_btn_checkable = 0;
    public static final int abc_tint_default = 0;
    public static final int abc_tint_edittext = 0;
    public static final int abc_tint_seek_thumb = 0;
    public static final int abc_tint_spinner = 0;
    public static final int abc_tint_switch_track = 0;
    public static final int accent_material_dark = 0;
    public static final int accent_material_light = 0;
    public static final int background_floating_material_dark = 0;
    public static final int background_floating_material_light = 0;
    public static final int background_material_dark = 0;
    public static final int background_material_light = 0;
    public static final int bright_foreground_disabled_material_dark = 0;
    public static final int bright_foreground_disabled_material_light = 0;
    public static final int bright_foreground_inverse_material_dark = 0;
    public static final int bright_foreground_inverse_material_light = 0;
    public static final int bright_foreground_material_dark = 0;
    public static final int bright_foreground_material_light = 0;
    public static final int button_material_dark = 0;
    public static final int button_material_light = 0;
    public static final int catalyst_logbox_background = 0;
    public static final int catalyst_redbox_background = 0;
    public static final int common_google_signin_btn_text_dark = 0;
    public static final int common_google_signin_btn_text_dark_default = 0;
    public static final int common_google_signin_btn_text_dark_disabled = 0;
    public static final int common_google_signin_btn_text_dark_focused = 0;
    public static final int common_google_signin_btn_text_dark_pressed = 0;
    public static final int common_google_signin_btn_text_light = 0;
    public static final int common_google_signin_btn_text_light_default = 0;
    public static final int common_google_signin_btn_text_light_disabled = 0;
    public static final int common_google_signin_btn_text_light_focused = 0;
    public static final int common_google_signin_btn_text_light_pressed = 0;
    public static final int common_google_signin_btn_tint = 0;
    public static final int dim_foreground_disabled_material_dark = 0;
    public static final int dim_foreground_disabled_material_light = 0;
    public static final int dim_foreground_material_dark = 0;
    public static final int dim_foreground_material_light = 0;
    public static final int error_color_material_dark = 0;
    public static final int error_color_material_light = 0;
    public static final int foreground_material_dark = 0;
    public static final int foreground_material_light = 0;
    public static final int highlighted_text_material_dark = 0;
    public static final int highlighted_text_material_light = 0;
    public static final int material_blue_grey_800 = 0;
    public static final int material_blue_grey_900 = 0;
    public static final int material_blue_grey_950 = 0;
    public static final int material_deep_teal_200 = 0;
    public static final int material_deep_teal_500 = 0;
    public static final int material_grey_100 = 0;
    public static final int material_grey_300 = 0;
    public static final int material_grey_50 = 0;
    public static final int material_grey_600 = 0;
    public static final int material_grey_800 = 0;
    public static final int material_grey_850 = 0;
    public static final int material_grey_900 = 0;
    public static final int notification_action_color_filter = 0;
    public static final int notification_icon_bg_color = 0;
    public static final int notification_material_background_media_default_color = 0;
    public static final int primary_dark_material_dark = 0;
    public static final int primary_dark_material_light = 0;
    public static final int primary_material_dark = 0;
    public static final int primary_material_light = 0;
    public static final int primary_text_default_material_dark = 0;
    public static final int primary_text_default_material_light = 0;
    public static final int primary_text_disabled_material_dark = 0;
    public static final int primary_text_disabled_material_light = 0;
    public static final int ripple_material_dark = 0;
    public static final int ripple_material_light = 0;
    public static final int secondary_text_default_material_dark = 0;
    public static final int secondary_text_default_material_light = 0;
    public static final int secondary_text_disabled_material_dark = 0;
    public static final int secondary_text_disabled_material_light = 0;
    public static final int switch_thumb_disabled_material_dark = 0;
    public static final int switch_thumb_disabled_material_light = 0;
    public static final int switch_thumb_material_dark = 0;
    public static final int switch_thumb_material_light = 0;
    public static final int switch_thumb_normal_material_dark = 0;
    public static final int switch_thumb_normal_material_light = 0;
    public static final int tooltip_background_dark = 0;
    public static final int tooltip_background_light = 0;

    static {
        C0201.m83(a.class, 213);
    }
}
